root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp/main.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["frontend", "node_modules"]

[color]
  main = "yellow"

